### ISSUE TITLE
Hardcoded table creation does not work on Oracle

### ISSUE THREAD

**Issue by ing-rafbhoedjang** [corda/corda-solutions#67]
See https://github.com/corda/corda-solutions/blob/1af6bd2d47ac7502d8ffe822c1266f5b9d42f04b/bn-apps/memberships-management/membership-service/src/main/kotlin/com/r3/businessnetworks/membership/bno/service/DatabaseService.kt#L28

The DatabaseService issues a SQL query that does not work on Oracle 12. (Apparently, 'IF NOT EXISTS' is not a standardized feature.)

Is there any reason for not using a Liquibase migration script to create this table?

**Comment by ivanr3** [comment]
Hi @ing-rafbhoedjang . Apologies for coming back late on this one. This has been fixed in the last version of BNMS (2.0). Please check it out.
